# syntax=docker/dockerfile:experimental
FROM us-docker.pkg.dev/streamline-resources/streamline-private-repo/streamliner-packages

RUN install2.r --error \ 
    shiny \
    shinydashboard \
    DT \
    flexdashboard \
    shinyjs \
    remotes \
    glue

RUN Rscript -e "remotes::install_github('muschellij2/googleCloudRunner')"
RUN Rscript -e "remotes::install_github('muschellij2/googleComputeEngineR')"
RUN Rscript -e "remotes::install_github('muschellij2/remotes')"

RUN ["mkdir", "-m", "700", "-p", "/root/.ssh/"]
COPY [".ssh/*", "/root/.ssh/"]
RUN eval $(ssh-agent) && chmod 600 /root/.ssh/id_rsa && echo "StrictHostKeyChecking no" >> /etc/ssh/ssh_config && ssh-add /root/.ssh/id_rsa
RUN ["git", "config", "--global", "user.name", "googleCloudRunner"]
RUN ["git", "config", "--global", "user.email", "cr_buildstep_gitsetup@googleCloudRunner.com"]

RUN Rscript -e "remotes::install_git('git@github.com:StreamlineDataScience/gcloud', git = 'external')"

COPY apps/ /srv/shiny-server/
RUN cat /srv/shiny-server/create_vm/index.Rmd

EXPOSE 3838
EXPOSE 8787

CMD ["/init"]
